2024-12-24 23:36:18,784 - WARNING - tests_12_4 - Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Тина\PycharmProjects\pythonProject12\tests_12_4.py", line 59, in test_run
    sprinter = Runner(name=50, speed=100)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Тина\PycharmProjects\pythonProject12\tests_12_4.py", line 10, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-24 23:36:18,787 - WARNING - tests_12_4 - Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Тина\PycharmProjects\pythonProject12\tests_12_4.py", line 47, in test_walk
    sprinter = Runner(name="Спринтер", speed=-100)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Тина\PycharmProjects\pythonProject12\tests_12_4.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -100
